### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by marty0801** [dfdx/Yota.jl#57]
I just started experimenting with Yota. (BTW, thanks for the great package!) 

I'm trying the derivative of a standard normal PDF, with @diffrule assigned using the closed-form expression for the derivative. Benchmarking shows that Yota-calculation of the derivative is orders of magnitude slower than evaluation of the closed-form derivative. This is obviously user error, but I can't spot it. Help? 

```
eval gradient function
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     6.352 ns (0.00% GC)
  median time:      8.598 ns (0.00% GC)
  mean time:        10.402 ns (0.00% GC)
  maximum time:     39.873 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     999

Yota gradient
BenchmarkTools.Trial: 
  memory estimate:  3.58 KiB
  allocs estimate:  49
  --------------
  minimum time:     9.191 μs (0.00% GC)
  median time:      10.175 μs (0.00% GC)
  mean time:        11.439 μs (0.00% GC)
  maximum time:     92.272 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

```

The code: 
```
using Revise
using Yota:grad, @diffrule, trace, compile!, play!
using BenchmarkTools: @benchmark, @btime

## Yota with diffrule for PDF
function ff(x)
    1/sqrt(2*pi)*exp(-x^2)
end
function dff(x)
    -2*x*ff(x)
end
@diffrule ff(x::Number) x (dff(x) .* dy)
function benchmarkgradient()
    println("\neval gradient function")
    display(@benchmark dff(x) setup=(x=rand()))
    println("\nYota gradient")
    display(@benchmark grad(ff,x) setup=(x=rand()))
end
```

**Comment by dfdx** [comment]
Try this instead: 

```julia
dfunc = simplegrad(ff, x)
@benchmark dfunc(x)
```
Which is already much better: 
```
BenchmarkTools.Trial: 
  memory estimate:  32 bytes
  allocs estimate:  1
  --------------
  minimum time:     32.733 ns (0.00% GC)
  median time:      34.438 ns (0.00% GC)
  mean time:        40.472 ns (6.64% GC)
  maximum time:     4.312 μs (98.33% GC)
  --------------
  samples:          10000
  evals/sample:     990
```
I'll come back to you with explanations and further options a bit later today.

**Comment by dfdx** [comment]
### Why `simplegrad()`?

`grad()` is optimized for machine learning tasks. In particular, it does 2 things: 

1. It uses pre-allocated buffers for most variables, spending some time at the beginning of function to set up the stage and at the end to clean it up. 
2. It uses `Base.invokelatest()` to be able to call gradient function compiled at the later world age (check out [this post](https://discourse.julialang.org/t/world-age-problem-explanation/9714/5) if you are not familiar with the concept of world age in Julia). 

Overhead, caused by these optimizations, is insignificant for tensor functions typically used in machine learning. But for small scalar functions the overhead is much larger than actual computation. And thus we have `simplegrad()`.

`simplegrad()` removes all such optimizations and generates ordinary function. You can check the code of this function using `@code_lowered`:

```julia
x = rand()
sdf = simplegrad(ff, x)
# ==> CodeInfo(
# ==> 1 ─      %2 = (ff)(%1)
# ==> │        %3 = 1.0
# ==> │        %4 = *
# ==> │        %5 = (dff)(%1)
# ==> │        %6 = (broadcast)(%4, %5, %3)
# ==> │   %6 = Core.tuple(%2, %6)
# ==> └──      return %6
# ==> )
```
Which gives median time of 34-38 ns.

### Better derivative definition

Note that in the lowered code above we call both - `ff(x)` and `dff(x)`, which already has `ff(x)` in its body. `@diffrule` lets you avoid duplication using special symbol `:y`:

```julia
@diffrule ff(x::Number) x (-2 * x * y)
```
This is basically definition of `dff()` where `ff()` is replaced with `y`. In general, `y` represents result of the call of the function in question, just like `dy` represents gradient of the loss function w.r.t. to this result. 
The lowered code now looks like: 

```julia
# ==> CodeInfo(
# ==> 1 ─      %2 = (ff)(%1)
# ==> │        %3 = 1.0
# ==> │        %4 = -2
# ==> │        %5 = (*)(%4, %1, %2)
# ==> │   %5 = Core.tuple(%2, %5)
# ==> └──      return %5
# ==> )
```
Essentially, this code is almost equivalent to your manual definition of `dff(x)` with a few additional lightweight operations. However, Julia 1.3 wasn't able to optimize it as well as manual version, and honestly I have very little understanding why. Maybe Julia 1.4 will handle it better, but didn't try it yet. 

For reference, here's the full code I used for tests:

```julia
using Yota
import Yota: simplegrad
using BenchmarkTools: @benchmark, @btime

## Yota with diffrule for PDF
function ff(x)
    1/sqrt(2*pi)*exp(-x^2)
end
function dff(x)
    -2*x*ff(x)
end

@diffrule ff(x::Number) x (-2 * x * y)

sdf = simplegrad(ff, rand())

function benchmarkgradient()
    println("\neval gradient function")
    display(@benchmark dff(x) setup=(x=rand()))
    println("\nYota gradient")
    display(@benchmark grad(ff,x) setup=(x=rand()))
    println("\nYota simplegrad")    
    display(@benchmark sdf(x) setup=(x=rand()))
end
```

**Comment by marty0801** [comment]
Wow outstanding! Thank you for that expansive and illuminating answer. 

Regarding optimization #1 above, is it possible to reuse previously-allocated buffers when calling gradient several times? (Is this the purpose of the 'tape' api? I couldn't figure out how to compute gradients with it.)

**Comment by dfdx** [comment]
Let me explain how all of these things fit together. 

### Tape

The very first thing you should know about is the `Tape`. `Tape` is a linearized representation of a function. The simplest way to obtain a tape is to trace a function call: 

```julia
import Yota: trace

function ff(x)
    1/sqrt(2*pi)*exp(-x^2)
end

val, tape = trace(ff, rand())
```
`val` is just the return value of the function and tape looks like this:

```julia
Tape
  inp %1::Float64
  const %2 = 2::Int64
  const %3 = π::Irrational{:π}
  %4 = *(%2, %3)::Float64
  %5 = sqrt(%4)::Float64
  const %6 = 1::Int64
  %7 = /(%6, %5)::Float64
  const %8 = Val{2}::DataType
  %9 = __new__(%8)::Val{2}
  const %10 = ^::typeof(^)
  %11 = literal_pow(%10, %1, %9)::Float64
  %12 = -(%11)::Float64
  %13 = exp(%12)::Float64
  %14 = *(%7, %13)::Float64
```
Tape consists of nodes of 4 types with self-explanatory names: `Input`, `Constant`, `Call` and `Assign` (the last one is usually eliminated during optimization). Although the tape might look overloaded, it just divides a single expression `1/sqrt(2*pi)*exp(-x^2)` into the set of primitives (e.g. `%4 = *(%2, %3)` comes from `2*pi`). 

### Gradient

Although in most cases you use `grad()` (or `simplegrad()`), internally the most important function is `_grad()` (with underscore), which boils down to:

```julia
tape = trace(f, args...)
back!(tape)
```
`back!()` iterates the tape in reverse order and for each node records its derivative. Try this:

```julia
import Yota._grad
val, g = _grad(ff, rand())
print(g.tape)
```
which gives us:
```julia
Tape
  inp %1::Float64
  const %2 = 2::Int64
  const %3 = π::Irrational{:π}
  %4 = *(%2, %3)::Float64
  %5 = sqrt(%4)::Float64
  const %6 = 1::Int64
  %7 = /(%6, %5)::Float64
  const %8 = Val{2}::DataType
  %9 = __new__(%8)::Val{2}
  const %10 = ^::typeof(^)
  %11 = literal_pow(%10, %1, %9)::Float64
  %12 = -(%11)::Float64
  %13 = exp(%12)::Float64
  %14 = *(%7, %13)::Float64
  const %15 = 1.0::Float64
  %16 = *(%13, %15)::Float64
  %17 = *(%7, %15)::Float64
  %18 = *(%13, %17)::Float64
  %19 = -(%18)::Float64
  %20 = get_val_param(%9)::Int64
  %21 = one(%1)::Float64
  %22 = -(%20, %21)::Float64
  %23 = ^(%1, %22)::Float64
  %24 = *(%20, %23, %19)::Float64
  %25 = -(%6)::Int64
  %26 = *(%25, %16)::Float64
  %27 = *(%5, %5)::Float64
  %28 = /(%26, %27)::Float64
  %29 = one(%4)::Float64
  const %30 = 2::Int64
  %31 = /(%29, %30)::Float64
  %32 = -(%29)::Float64
  const %33 = 2::Int64
  %34 = /(%32, %33)::Float64
  %35 = ^(%4, %34)::Float64
  %36 = *(%31, %35, %28)::Float64
```
First half of the tape stays exactly the same, and the rest consists of nodes needed to calculated gradient of the function w.r.t to input parameter. 

### Compilation

At this point we already can "play!" the tape with new arguments and extract derivatives using helper type `GradResult`:

```julia
import Yota: play!

play!(g.tape, rand())
print(g[1])
```
But we can additionally generate a function from this tape to speed up things:

```julia
import Yota: generate_function_expr, generate_function_expr_unbound
generate_function_expr(g.tape)
```
which creates an expression like this:
```julia
function var"##tape_fn#402"()
      #= prologue:0 =#
      var"%1" = (inp %1::Float64).val
      var"%2" = (const %2 = 2::Int64).val
      var"%3" = (const %3 = π::Irrational{:π}).val
      var"%4" = (%4 = *(%2, %3)::Float64).val
      var"%5" = (%5 = sqrt(%4)::Float64).val
      var"%6" = (const %6 = 1::Int64).val
      var"%7" = (%7 = /(%6, %5)::Float64).val
      var"%8" = (const %8 = Val{2}::DataType).val
      var"%9" = (%9 = __new__(%8)::Val{2}).val
      var"%10" = (const %10 = ^::typeof(^)).val
      var"%11" = (%11 = literal_pow(%10, %1, %9)::Float64).val
      var"%12" = (%12 = -(%11)::Float64).val
      var"%13" = (%13 = exp(%12)::Float64).val
      var"%14" = (%14 = *(%7, %13)::Float64).val
      var"%15" = (const %15 = 1.0::Float64).val
      var"%16" = (%16 = *(%13, %15)::Float64).val
      var"%17" = (%17 = *(%7, %15)::Float64).val
      var"%18" = (%18 = *(%13, %17)::Float64).val
      var"%19" = (%19 = -(%18)::Float64).val
      var"%20" = (%20 = get_val_param(%9)::Int64).val
      var"%21" = (%21 = one(%1)::Float64).val
      var"%22" = (%22 = -(%20, %21)::Float64).val
      var"%23" = (%23 = ^(%1, %22)::Float64).val
      var"%24" = (%24 = *(%20, %23, %19)::Float64).val
      var"%25" = (%25 = -(%6)::Int64).val
      var"%26" = (%26 = *(%25, %16)::Float64).val
      var"%27" = (%27 = *(%5, %5)::Float64).val
      var"%28" = (%28 = /(%26, %27)::Float64).val
      var"%29" = (%29 = one(%4)::Float64).val
      var"%30" = (const %30 = 2::Int64).val
      var"%31" = (%31 = /(%29, %30)::Float64).val
      var"%32" = (%32 = -(%29)::Float64).val
      var"%33" = (const %33 = 2::Int64).val
      var"%34" = (%34 = /(%32, %33)::Float64).val
      var"%35" = (%35 = ^(%4, %34)::Float64).val
      var"%36" = (%36 = *(%31, %35, %28)::Float64).val
      #= body:0 =#
      ()
      var"%2" = 2
      var"%3" = π
      var"%4" = (*)(var"%2", var"%3")
      var"%5" = (sqrt)(var"%4")
      var"%6" = 1
      var"%7" = (/)(var"%6", var"%5")
      var"%8" = Val{2}
      var"%9" = (Yota.__new__)(var"%8")
      var"%10" = ^
      var"%11" = (Base.literal_pow)(var"%10", var"%1", var"%9")
      var"%12" = (-)(var"%11")
      var"%13" = (exp)(var"%12")
      var"%14" = (*)(var"%7", var"%13")
      var"%15" = 1.0
      var"%16" = (*)(var"%13", var"%15")
      var"%17" = (*)(var"%7", var"%15")
      var"%18" = (*)(var"%13", var"%17")
      var"%19" = (-)(var"%18")
      var"%20" = (Yota.get_val_param)(var"%9")
      var"%21" = (one)(var"%1")
      var"%22" = (-)(var"%20", var"%21")
      var"%23" = (^)(var"%1", var"%22")
      var"%24" = (*)(var"%20", var"%23", var"%19")
      var"%25" = (-)(var"%6")
      var"%26" = (*)(var"%25", var"%16")
      var"%27" = (*)(var"%5", var"%5")
      var"%28" = (/)(var"%26", var"%27")
      var"%29" = (one)(var"%4")
      var"%30" = 2
      var"%31" = (/)(var"%29", var"%30")
      var"%32" = (-)(var"%29")
      var"%33" = 2
      var"%34" = (/)(var"%32", var"%33")
      var"%35" = (^)(var"%4", var"%34")
      var"%36" = (*)(var"%31", var"%35", var"%28")
      #= epilogue:0 =#
      (inp %1::Float64).val = var"%1"
      (const %2 = 2::Int64).val = var"%2"
      (const %3 = π::Irrational{:π}).val = var"%3"
      (%4 = *(%2, %3)::Float64).val = var"%4"
      (%5 = sqrt(%4)::Float64).val = var"%5"
      (const %6 = 1::Int64).val = var"%6"
      (%7 = /(%6, %5)::Float64).val = var"%7"
      (const %8 = Val{2}::DataType).val = var"%8"
      (%9 = __new__(%8)::Val{2}).val = var"%9"
      (const %10 = ^::typeof(^)).val = var"%10"
      (%11 = literal_pow(%10, %1, %9)::Float64).val = var"%11"
      (%12 = -(%11)::Float64).val = var"%12"
      (%13 = exp(%12)::Float64).val = var"%13"
      (%14 = *(%7, %13)::Float64).val = var"%14"
      (const %15 = 1.0::Float64).val = var"%15"
      (%16 = *(%13, %15)::Float64).val = var"%16"
      (%17 = *(%7, %15)::Float64).val = var"%17"
      (%18 = *(%13, %17)::Float64).val = var"%18"
      (%19 = -(%18)::Float64).val = var"%19"
      (%20 = get_val_param(%9)::Int64).val = var"%20"
      (%21 = one(%1)::Float64).val = var"%21"
      (%22 = -(%20, %21)::Float64).val = var"%22"
      (%23 = ^(%1, %22)::Float64).val = var"%23"
      (%24 = *(%20, %23, %19)::Float64).val = var"%24"
      (%25 = -(%6)::Int64).val = var"%25"
      (%26 = *(%25, %16)::Float64).val = var"%26"
      (%27 = *(%5, %5)::Float64).val = var"%27"
      (%28 = /(%26, %27)::Float64).val = var"%28"
      (%29 = one(%4)::Float64).val = var"%29"
      (const %30 = 2::Int64).val = var"%30"
      (%31 = /(%29, %30)::Float64).val = var"%31"
      (%32 = -(%29)::Float64).val = var"%32"
      (const %33 = 2::Int64).val = var"%33"
      (%34 = /(%32, %33)::Float64).val = var"%34"
      (%35 = ^(%4, %34)::Float64).val = var"%35"
      (%36 = *(%31, %35, %28)::Float64).val = var"%36"
  end
```
This code is split into 3 parts: 

1. Prologue - assigning new variable names to values stored on the tape.
2. Body, which closely follows nodes on the tape, but rewrites some function calls to their in-place versions.
3. Epilogue - saving new values back to the tape. 

Prologue and epilogue are typically very lightweight for tensor functions, but for scalar ones they may take most of the time. And so we also have `generate_function_expr_unbound`, which avoids any references to the tape and generates plain old function. 

This expressions is then compiled and saved to the field of the tape. 

### Caching

Since tracing takes quite a lot of time (~90-95% of the first call), we want to do it only once. `grad()` wraps `_grad()` and adds caching layer (you can even reset this cache using `empty!(Yota.GRAD_CACHE)`). Again, for tensor functions this caching is negligible, but for scalar ones it may be better to avoid it by using `simplegrad()` which returns compiled function only and never re-traces call anyway. 

So, answering your questions about pre-allocated buffers, - it will happen automatically if you use `grad()`, but for scalar functions it doesn't make much sense (scalars are `isbits`, and `isbits` types are copied anyway).

**Comment by marty0801** [comment]
Thank you!
